steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'southamerica-east1-docker.pkg.dev/devopssaocarlosmonks/docker-main-app/hello-world:v1', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'southamerica-east1-docker.pkg.dev/devopssaocarlosmonks/docker-main-app/hello-world:v1']
