steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'southamerica-east1-docker.pkg.dev/devopssaocarlosmonks/docker-main-app/hello-world:$SHORT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'southamerica-east1-docker.pkg.dev/devopssaocarlosmonks/docker-main-app/hello-world:$SHORT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - > 
    gcloud deploy releases create release-$BUILD_ID
    --delivery-pipeline=hello-world-app
    --region=southamerica-east1
    --source=./
    --images=southamerica-east1-docker.pkg.dev/devopssaocarlosmonks/docker-main-app/hello-world:$SHORT_SHA 
